/* eslint-disable */
/* auto-generated by napi-rs */

const { existsSync, readFileSync } = require('fs')
const { join } = require('path')

const { platform, arch } = process

let nativeBinding = null
let localFileExisted = false
let loadError = null

function isMusl() {
  // For Node 12+, use the `report` API for detecting musl
  if (typeof process.report?.getReport === 'function') {
    const report = process.report.getReport()
    const sharedObjects = typeof report === 'string'
      ? JSON.parse(report).sharedObjects
      : report?.sharedObjects
    if (Array.isArray(sharedObjects)) {
      return sharedObjects.some((lib) => lib.includes('libc.musl-') || lib.includes('ld-musl-'))
    }
  }
  try {
    return readFileSync('/usr/bin/ldd', 'utf8').includes('musl')
  } catch {
    return false
  }
}

switch (platform) {
  case 'win32':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'signal-native.win32-x64-msvc.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./signal-native.win32-x64-msvc.node')
          } else {
            nativeBinding = require('@milady/signal-native-win32-x64-msvc')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Windows: ${arch}`)
    }
    break
  case 'darwin':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'signal-native.darwin-x64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./signal-native.darwin-x64.node')
          } else {
            nativeBinding = require('@milady/signal-native-darwin-x64')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'signal-native.darwin-arm64.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./signal-native.darwin-arm64.node')
          } else {
            nativeBinding = require('@milady/signal-native-darwin-arm64')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on macOS: ${arch}`)
    }
    break
  case 'linux':
    switch (arch) {
      case 'x64':
        localFileExisted = existsSync(join(__dirname, 'signal-native.linux-x64-gnu.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./signal-native.linux-x64-gnu.node')
          } else {
            nativeBinding = require('@milady/signal-native-linux-x64-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      case 'arm64':
        localFileExisted = existsSync(join(__dirname, 'signal-native.linux-arm64-gnu.node'))
        try {
          if (localFileExisted) {
            nativeBinding = require('./signal-native.linux-arm64-gnu.node')
          } else {
            nativeBinding = require('@milady/signal-native-linux-arm64-gnu')
          }
        } catch (e) {
          loadError = e
        }
        break
      default:
        throw new Error(`Unsupported architecture on Linux: ${arch}`)
    }
    break
  default:
    throw new Error(`Unsupported OS: ${platform}, architecture: ${arch}`)
}

if (!nativeBinding) {
  if (loadError) {
    throw loadError
  }
  throw new Error(`Failed to load native binding`)
}

module.exports.linkDevice = nativeBinding.linkDevice
module.exports.finishLink = nativeBinding.finishLink
module.exports.register = nativeBinding.register
module.exports.confirmRegistration = nativeBinding.confirmRegistration
module.exports.sendMessage = nativeBinding.sendMessage
module.exports.sendGroupMessage = nativeBinding.sendGroupMessage
module.exports.receiveMessages = nativeBinding.receiveMessages
module.exports.stopReceiving = nativeBinding.stopReceiving
module.exports.listContacts = nativeBinding.listContacts
module.exports.listGroups = nativeBinding.listGroups
module.exports.sendReaction = nativeBinding.sendReaction
module.exports.getProfile = nativeBinding.getProfile
