/* auto-generated by napi-rs */
/* eslint-disable */

export interface JsSendResult {
  timestamp: number
}

export interface JsContact {
  uuid: string
  phoneNumber?: string | null
  name?: string | null
}

export interface JsGroup {
  id: string
  name: string
  description?: string | null
  membersCount: number
}

export interface JsProfile {
  uuid: string
  phoneNumber?: string | null
}

export interface JsAttachment {
  contentType: string
  fileName?: string | null
  size?: number | null
}

export interface JsIncomingMessage {
  senderUuid: string
  timestamp: number
  text?: string | null
  groupId?: string | null
  isReaction: boolean
  reactionEmoji?: string | null
  reactionTargetTimestamp?: number | null
  attachments: JsAttachment[]
  isQueueEmpty: boolean
}

/**
 * Link as a secondary device. Returns the provisioning URL to encode as QR.
 * Call `finishLink()` after the user scans the QR code.
 */
export declare function linkDevice(dataPath: string, deviceName: string): Promise<string>

/**
 * Wait for device linking to complete after the user has scanned the QR code.
 */
export declare function finishLink(dataPath: string): Promise<void>

/**
 * Register as a primary device. Not yet implemented — use linkDevice().
 */
export declare function register(dataPath: string, phoneNumber: string, useVoice: boolean): Promise<void>

/**
 * Confirm registration. Not yet implemented — use linkDevice().
 */
export declare function confirmRegistration(dataPath: string, code: string): Promise<void>

/**
 * Send a text message to a recipient identified by their ServiceId string.
 */
export declare function sendMessage(dataPath: string, recipient: string, text: string): Promise<JsSendResult>

/**
 * Send a text message to a group identified by hex-encoded master key.
 */
export declare function sendGroupMessage(dataPath: string, groupMasterKeyHex: string, text: string): Promise<JsSendResult>

/**
 * Start receiving messages. Creates a dedicated manager instance for receiving.
 */
export declare function receiveMessages(dataPath: string, callback: (message: JsIncomingMessage) => void): Promise<void>

/**
 * Stop the receive loop for the given data path.
 */
export declare function stopReceiving(dataPath: string): Promise<void>

/**
 * List all stored contacts.
 */
export declare function listContacts(dataPath: string): Promise<JsContact[]>

/**
 * List all stored groups.
 */
export declare function listGroups(dataPath: string): Promise<JsGroup[]>

/**
 * Send a reaction emoji to a specific message.
 */
export declare function sendReaction(dataPath: string, recipient: string, emoji: string, targetTimestamp: number): Promise<void>

/**
 * Get the registered device's own profile information.
 */
export declare function getProfile(dataPath: string): Promise<JsProfile>
